import axios from "axios";
import Head from "next/head";
import { useState, useEffect } from "react";
import { Header } from "./layouts/Header/Header";

const Home = () => {
  const [cards, setCards] = useState(null);

  useEffect(() => {
    const fetchCards = async () => {
      try {
        const response = await axios.get(
          "https://65bb606a52189914b5bbe878.mockapi.io/items"
        );
        setCards(response.data);
      } catch (err) {
        console.error("Error fetching cards:", err);
      }
    };

    fetchCards();
  }, []);

  return (
    <>
      <Head>
        <title>Share.tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </>
  );
};

export default Home;
